# =============================================================================
# plot_pve_cdf_null_envelope.R
#
# Purpose: Build the PVE cumulative distribution figure (proposed Figure S12),
#          showing the observed cumulative PVE curve against a null envelope
#          generated by permuting LD50 across the 12 lines 1,000 times
#          (see pve_cdf_and_null_envelope.R, run on Savio).
#
# Input:  pve_cdf_with_null_envelope.csv
#         (window_rank, window_fraction, observed_cumulative_PVE,
#          null_mean_cumulative_PVE, null_lower_2.5, null_upper_97.5)
#
# Output: FigureS12_PVE_cumulative_distribution.pdf
# =============================================================================

library(ggplot2)
library(scales)

d <- read.csv("pve_cdf_with_null_envelope.csv", stringsAsFactors = FALSE)

# Sanity check before plotting -- confirm this matches the console output
# from the Savio run (2,164 rows; observed 4.7%/55.2% at top1%/top25%)
cat("Rows:", nrow(d), "(expect 2164)\n")
top1_idx  <- which.min(abs(d$window_fraction - 0.01))
top25_idx <- which.min(abs(d$window_fraction - 0.25))
cat("Observed at ~top 1%:", round(100 * d$observed_cumulative_PVE[top1_idx], 1), "%\n")
cat("Observed at ~top 25%:", round(100 * d$observed_cumulative_PVE[top25_idx], 1), "%\n")

p <- ggplot(d, aes(x = window_fraction)) +
  # Null envelope (2.5th-97.5th percentile band across 1,000 LD50 permutations)
  geom_ribbon(aes(ymin = null_lower_2.5, ymax = null_upper_97.5),
              fill = "grey70", alpha = 0.5) +
  geom_line(aes(y = null_mean_cumulative_PVE),
            color = "grey40", linetype = "dashed", linewidth = 0.6) +
  # Observed curve
  geom_line(aes(y = observed_cumulative_PVE),
            color = "blue", linewidth = 0.9) +
  scale_x_continuous(labels = percent_format(accuracy = 1)) +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  labs(
    title = "Cumulative distribution of variance explained (PVE) across windows",
    x = "Fraction of windows (ranked by PVE, descending)",
    y = "Cumulative share of total PVE",
    caption = "Grey band: 95% null envelope from 1,000 permutations of LD50 across lines.\nDashed line: null mean. Blue line: observed."
  ) +
  theme_minimal() +
  theme(
    plot.title   = element_text(size = 12, face = "bold"),
    plot.caption = element_text(size = 8, hjust = 0, color = "grey30"),
    axis.title   = element_text(size = 10)
  )

p

ggsave("FigureS12_PVE_cumulative_distribution.pdf", p, width = 7, height = 5)
cat("\nSaved FigureS12_PVE_cumulative_distribution.pdf\n")
